#define BGCOLOR 0x0
#define FGCOLOR 0xFFFF

#define _SCREEN_DATE_X 80
#define _SCREEN_DATE_Y 0
#define _SCREEN_DATE_SIZE 1

#define _SCREEN_TIME_X 80
#define _SCREEN_TIME_Y 20
#define _SCREEN_TIME_SIZE 1

#define _SCREEN_TEMP_X 80
#define _SCREEN_TEMP_Y 40
#define _SCREEN_TEMP_SIZE 1

#define _SCREEN_PRESSURE_X 80
#define _SCREEN_PRESSURE_Y 60
#define _SCREEN_PRESSURE_SIZE 1

#define _SCREEN_HUMIDITY_X 80
#define _SCREEN_HUMIDITY_Y 80
#define _SCREEN_HUMIDITY_SIZE 1