// #ifndef __CONFIG_ADV__
// #define __CONFIG_ADV__
// #endif

#define _LCD_TIME_START_POSITION_X 0
#define _LCD_TIME_START_POSITION_Y 0
#define _LCD_DATE_START_POSITION_X 0
#define _LCD_DATE_START_POSITION_Y 1
#define _LCD_TEMP_START_POSITION_X 9
#define _LCD_TEMP_START_POSITION_Y 0
#define _LCD_HUMIDITY_START_POSITION_X 12
#define _LCD_HUMIDITY_START_POSITION_Y 1
